window.COUNTRIES = [
  { name: "Afghanistan", code: "af", aliases: [] },
  { name: "Albania", code: "al", aliases: [] },
  { name: "Algeria", code: "dz", aliases: [] },
  { name: "Andorra", code: "ad", aliases: [] },
  { name: "Angola", code: "ao", aliases: [] },
  { name: "Antigua and Barbuda", code: "ag", aliases: [] },
  { name: "Argentina", code: "ar", aliases: [] },
  { name: "Armenia", code: "am", aliases: [] },
  { name: "Australia", code: "au", aliases: [] },
  { name: "Austria", code: "at", aliases: [] },
  { name: "Azerbaijan", code: "az", aliases: [] },
  { name: "Bahamas", code: "bs", aliases: [] },
  { name: "Bahrain", code: "bh", aliases: [] },
  { name: "Bangladesh", code: "bd", aliases: [] },
  { name: "Barbados", code: "bb", aliases: [] },
  { name: "Belarus", code: "by", aliases: [] },
  { name: "Belgium", code: "be", aliases: [] },
  { name: "Belize", code: "bz", aliases: [] },
  { name: "Benin", code: "bj", aliases: [] },
  { name: "Bhutan", code: "bt", aliases: [] },
  { name: "Bolivia", code: "bo", aliases: [] },
  { name: "Bosnia and Herzegovina", code: "ba", aliases: ["bosnia"] },
  { name: "Botswana", code: "bw", aliases: [] },
  { name: "Brazil", code: "br", aliases: [] },
  { name: "Brunei", code: "bn", aliases: ["brunei darussalam"] },
  { name: "Bulgaria", code: "bg", aliases: [] },
  { name: "Burkina Faso", code: "bf", aliases: [] },
  { name: "Burundi", code: "bi", aliases: [] },
  { name: "Cabo Verde", code: "cv", aliases: ["cape verde"] },
  { name: "Cambodia", code: "kh", aliases: [] },
  { name: "Cameroon", code: "cm", aliases: [] },
  { name: "Canada", code: "ca", aliases: [] },
  { name: "Central African Republic", code: "cf", aliases: [] },
  { name: "Chad", code: "td", aliases: [] },
  { name: "Chile", code: "cl", aliases: [] },
  { name: "China", code: "cn", aliases: ["people's republic of china", "pr china"] },
  { name: "Colombia", code: "co", aliases: [] },
  { name: "Comoros", code: "km", aliases: [] },
  { name: "Costa Rica", code: "cr", aliases: [] },
  { name: "Croatia", code: "hr", aliases: [] },
  { name: "Cuba", code: "cu", aliases: [] },
  { name: "Cyprus", code: "cy", aliases: [] },
  { name: "Czechia", code: "cz", aliases: ["czech republic"] },
  { name: "Democratic Republic of the Congo", code: "cd", aliases: ["dr congo", "drc", "congo kinshasa"] },
  { name: "Denmark", code: "dk", aliases: [] },
  { name: "Djibouti", code: "dj", aliases: [] },
  { name: "Dominica", code: "dm", aliases: [] },
  { name: "Dominican Republic", code: "do", aliases: [] },
  { name: "Ecuador", code: "ec", aliases: [] },
  { name: "Egypt", code: "eg", aliases: [] },
  { name: "El Salvador", code: "sv", aliases: [] },
  { name: "Equatorial Guinea", code: "gq", aliases: [] },
  { name: "Eritrea", code: "er", aliases: [] },
  { name: "Estonia", code: "ee", aliases: [] },
  { name: "Eswatini", code: "sz", aliases: ["swaziland"] },
  { name: "Ethiopia", code: "et", aliases: [] },
  { name: "Fiji", code: "fj", aliases: [] },
  { name: "Finland", code: "fi", aliases: [] },
  { name: "France", code: "fr", aliases: [] },
  { name: "Gabon", code: "ga", aliases: [] },
  { name: "Gambia", code: "gm", aliases: ["the gambia"] },
  { name: "Georgia", code: "ge", aliases: [] },
  { name: "Germany", code: "de", aliases: [] },
  { name: "Ghana", code: "gh", aliases: [] },
  { name: "Greece", code: "gr", aliases: [] },
  { name: "Grenada", code: "gd", aliases: [] },
  { name: "Guatemala", code: "gt", aliases: [] },
  { name: "Guinea", code: "gn", aliases: [] },
  { name: "Guinea-Bissau", code: "gw", aliases: [] },
  { name: "Guyana", code: "gy", aliases: [] },
  { name: "Haiti", code: "ht", aliases: [] },
  { name: "Honduras", code: "hn", aliases: [] },
  { name: "Hungary", code: "hu", aliases: [] },
  { name: "Iceland", code: "is", aliases: [] },
  { name: "India", code: "in", aliases: [] },
  { name: "Indonesia", code: "id", aliases: [] },
  { name: "Iran", code: "ir", aliases: ["iran, islamic republic of"] },
  { name: "Iraq", code: "iq", aliases: [] },
  { name: "Ireland", code: "ie", aliases: [] },
  { name: "Israel", code: "il", aliases: [] },
  { name: "Italy", code: "it", aliases: [] },
  { name: "Jamaica", code: "jm", aliases: [] },
  { name: "Japan", code: "jp", aliases: [] },
  { name: "Jordan", code: "jo", aliases: [] },
  { name: "Kazakhstan", code: "kz", aliases: [] },
  { name: "Kenya", code: "ke", aliases: [] },
  { name: "Kiribati", code: "ki", aliases: [] },
  { name: "Kuwait", code: "kw", aliases: [] },
  { name: "Kyrgyzstan", code: "kg", aliases: [] },
  { name: "Laos", code: "la", aliases: ["lao people's democratic republic"] },
  { name: "Latvia", code: "lv", aliases: [] },
  { name: "Lebanon", code: "lb", aliases: [] },
  { name: "Lesotho", code: "ls", aliases: [] },
  { name: "Liberia", code: "lr", aliases: [] },
  { name: "Libya", code: "ly", aliases: [] },
  { name: "Liechtenstein", code: "li", aliases: [] },
  { name: "Lithuania", code: "lt", aliases: [] },
  { name: "Luxembourg", code: "lu", aliases: [] },
  { name: "Madagascar", code: "mg", aliases: [] },
  { name: "Malawi", code: "mw", aliases: [] },
  { name: "Malaysia", code: "my", aliases: [] },
  { name: "Maldives", code: "mv", aliases: [] },
  { name: "Mali", code: "ml", aliases: [] },
  { name: "Malta", code: "mt", aliases: [] },
  { name: "Marshall Islands", code: "mh", aliases: [] },
  { name: "Mauritania", code: "mr", aliases: [] },
  { name: "Mauritius", code: "mu", aliases: [] },
  { name: "Mexico", code: "mx", aliases: [] },
  { name: "Micronesia", code: "fm", aliases: ["federated states of micronesia"] },
  { name: "Moldova", code: "md", aliases: ["republic of moldova"] },
  { name: "Monaco", code: "mc", aliases: [] },
  { name: "Mongolia", code: "mn", aliases: [] },
  { name: "Montenegro", code: "me", aliases: [] },
  { name: "Morocco", code: "ma", aliases: [] },
  { name: "Mozambique", code: "mz", aliases: [] },
  { name: "Myanmar", code: "mm", aliases: ["burma"] },
  { name: "Namibia", code: "na", aliases: [] },
  { name: "Nauru", code: "nr", aliases: [] },
  { name: "Nepal", code: "np", aliases: [] },
  { name: "Netherlands", code: "nl", aliases: ["holland"] },
  { name: "New Zealand", code: "nz", aliases: [] },
  { name: "Nicaragua", code: "ni", aliases: [] },
  { name: "Niger", code: "ne", aliases: [] },
  { name: "Nigeria", code: "ng", aliases: [] },
  { name: "North Korea", code: "kp", aliases: ["democratic people's republic of korea"] },
  { name: "North Macedonia", code: "mk", aliases: ["macedonia"] },
  { name: "Norway", code: "no", aliases: [] },
  { name: "Oman", code: "om", aliases: [] },
  { name: "Pakistan", code: "pk", aliases: [] },
  { name: "Palau", code: "pw", aliases: [] },
  { name: "Panama", code: "pa", aliases: [] },
  { name: "Papua New Guinea", code: "pg", aliases: [] },
  { name: "Paraguay", code: "py", aliases: [] },
  { name: "Peru", code: "pe", aliases: [] },
  { name: "Philippines", code: "ph", aliases: [] },
  { name: "Poland", code: "pl", aliases: [] },
  { name: "Portugal", code: "pt", aliases: [] },
  { name: "Qatar", code: "qa", aliases: [] },
  { name: "Republic of the Congo", code: "cg", aliases: ["congo brazzaville"] },
  { name: "Romania", code: "ro", aliases: [] },
  { name: "Russia", code: "ru", aliases: ["russian federation"] },
  { name: "Rwanda", code: "rw", aliases: [] },
  { name: "Saint Kitts and Nevis", code: "kn", aliases: [] },
  { name: "Saint Lucia", code: "lc", aliases: [] },
  { name: "Saint Vincent and the Grenadines", code: "vc", aliases: [] },
  { name: "Samoa", code: "ws", aliases: [] },
  { name: "San Marino", code: "sm", aliases: [] },
  { name: "Sao Tome and Principe", code: "st", aliases: ["sao tome"] },
  { name: "Saudi Arabia", code: "sa", aliases: [] },
  { name: "Senegal", code: "sn", aliases: [] },
  { name: "Serbia", code: "rs", aliases: [] },
  { name: "Seychelles", code: "sc", aliases: [] },
  { name: "Sierra Leone", code: "sl", aliases: [] },
  { name: "Singapore", code: "sg", aliases: [] },
  { name: "Slovakia", code: "sk", aliases: [] },
  { name: "Slovenia", code: "si", aliases: [] },
  { name: "Solomon Islands", code: "sb", aliases: [] },
  { name: "Somalia", code: "so", aliases: [] },
  { name: "South Africa", code: "za", aliases: [] },
  { name: "South Korea", code: "kr", aliases: ["republic of korea", "korea"] },
  { name: "South Sudan", code: "ss", aliases: [] },
  { name: "Spain", code: "es", aliases: [] },
  { name: "Sri Lanka", code: "lk", aliases: [] },
  { name: "Sudan", code: "sd", aliases: [] },
  { name: "Suriname", code: "sr", aliases: [] },
  { name: "Sweden", code: "se", aliases: [] },
  { name: "Switzerland", code: "ch", aliases: [] },
  { name: "Syria", code: "sy", aliases: ["syrian arab republic"] },
  { name: "Tajikistan", code: "tj", aliases: [] },
  { name: "Tanzania", code: "tz", aliases: ["united republic of tanzania"] },
  { name: "Thailand", code: "th", aliases: [] },
  { name: "Timor-Leste", code: "tl", aliases: ["east timor"] },
  { name: "Togo", code: "tg", aliases: [] },
  { name: "Tonga", code: "to", aliases: [] },
  { name: "Trinidad and Tobago", code: "tt", aliases: [] },
  { name: "Tunisia", code: "tn", aliases: [] },
  { name: "Turkey", code: "tr", aliases: ["turkiye"] },
  { name: "Turkmenistan", code: "tm", aliases: [] },
  { name: "Tuvalu", code: "tv", aliases: [] },
  { name: "Uganda", code: "ug", aliases: [] },
  { name: "Ukraine", code: "ua", aliases: [] },
  { name: "United Arab Emirates", code: "ae", aliases: ["uae"] },
  { name: "United Kingdom", code: "gb", aliases: ["uk", "great britain", "britain"] },
  { name: "United States", code: "us", aliases: ["usa", "us", "united states of america", "america"] },
  { name: "Uruguay", code: "uy", aliases: [] },
  { name: "Uzbekistan", code: "uz", aliases: [] },
  { name: "Vanuatu", code: "vu", aliases: [] },
  { name: "Vatican City", code: "va", aliases: ["holy see"] },
  { name: "Venezuela", code: "ve", aliases: [] },
  { name: "Vietnam", code: "vn", aliases: ["viet nam"] },
  { name: "Yemen", code: "ye", aliases: [] },
  { name: "Zambia", code: "zm", aliases: [] },
  { name: "Zimbabwe", code: "zw", aliases: [] }
];
