export const state = {
  target: null,
  guesses: [],
  suggestedCorrection: null,
  countrySuggestions: [],
  highlightedSuggestionIndex: -1,
  finished: false,
  finishReason: null,
  restoringRound: false,
  elapsedMsAtFinish: 0,
  revealOrder: [],
  revealedTiles: 0,
  gameType: "flag",
  playMode: "daily",
  dailySchedules: {
    flag: { entries: [], lookup: new Map(), meta: null },
    globe: { entries: [], lookup: new Map(), meta: null },
    capitals: { entries: [], lookup: new Map(), meta: null }
  },
  dailyDateKey: null,
  centroids: new Map(),
  atlasFeatures: [],
  atlasOverviewFeatureByCode: new Map(),
  atlasFeatureByCode: new Map(),
  marineFeatureByName: new Map(),
  globeFeatures: [],
  globeRotation: [-20, -18, 0],
  globeZoom: 1,
  globeDragVector: null,
  globeRotationStart: null,
  globeRotationQuaternion: null,
  globeDragging: false,
  globeRenderQueued: false,
  globeProjection: null,
  globePath: null,
  globeAnimationFrame: null,
  atlasCountries: [],
  atlasSet: "world",
  atlasQueue: [],
  capitalsRegion: "world",
  hintsEnabled: false,
  atlasIndex: 0,
  atlasAnswered: false,
  atlasAdvanceTimer: null,
  atlasShowRemaining: false,
  atlasSelectedCountryCode: null,
  atlasZoomBehavior: null,
  lookalikeGroup: null,
  lookalikeTarget: null,
  lookalikeScore: { correct: 0, total: 0, streak: 0, bestStreak: 0 },
  lookalikeAnswered: false,
  lookalikeAdvanceTimer: null,
  atlasMapLayer: null,
  atlasCountryPaths: null,
  atlasTinyCountryMarkers: null,
  atlasCountryPathByCode: new Map(),
  atlasTinyMarkerByCode: new Map(),
  atlasMapPath: null,
  atlasPathCache: new Map(),
  atlasPathCacheEntry: null,
  atlasDetailIdleCancel: null,
  atlasMapDetail: null,
  atlasRenderKey: null,
  atlasZoomFrame: null,
  atlasPanAnimationFrame: null,
  atlasPendingTransform: null,
  palette: "sage",
  siteZoom: 1,
  soundEnabled: true,
  recognitionOptions: { taiwan: false, kosovo: false },
  timerStartedAt: null,
  timerInterval: null
};

export const elements = {
  confettiCanvas: document.querySelector("#confetti-canvas"),
  flagGameButton: document.querySelector("#flag-game-button"),
  globleGameButton: document.querySelector("#globle-game-button"),
  atlasGameButton: document.querySelector("#atlas-game-button"),
  capitalsGameButton: document.querySelector("#capitals-game-button"),
  lookalikeGameButton: document.querySelector("#lookalike-game-button"),
  atlasSetControl: document.querySelector("#atlas-set-control"),
  capitalsRegionControl: document.querySelector("#capitals-region-control"),
  capitalsRegionSelect: document.querySelector("#capitals-region-select"),
  capitalStage: document.querySelector("#capital-stage"),
  capitalCountryName: document.querySelector("#capital-country-name"),
  capitalFlagFrame: document.querySelector("#capital-flag-frame"),
  capitalFlagImage: document.querySelector("#capital-flag-image"),
  lookalikeStage: document.querySelector("#lookalike-stage"),
  lookalikeCountryName: document.querySelector("#lookalike-country-name"),
  lookalikeFlagsGrid: document.querySelector("#lookalike-flags-grid"),
  hintsSwitch: document.querySelector("#hints-switch"),
  hintsOffButton: document.querySelector("#hints-off-button"),
  hintsOnButton: document.querySelector("#hints-on-button"),
  sidebarHints: document.querySelector("#sidebar-hints"),
  hintsDots: document.querySelector("#hints-dots"),
  hintCard: document.querySelector("#hint-card"),
  hintCardNumber: document.querySelector("#hint-card-number"),
  hintCardText: document.querySelector("#hint-card-text"),
  hintPrevButton: document.querySelector("#hint-prev"),
  hintNextButton: document.querySelector("#hint-next"),
  dailyModeButton: document.querySelector("#daily-mode-button"),
  unlimitedModeButton: document.querySelector("#unlimited-mode-button"),
  playModeSwitch: document.querySelector("#play-mode-switch"),
  atlasSetSelect: document.querySelector("#atlas-set-select"),
  gameCenter: document.querySelector("#game-center"),
  atlasStage: document.querySelector("#atlas-stage"),
  atlasHeading: document.querySelector("#atlas-heading"),
  atlasMapShell: document.querySelector("#atlas-map-shell"),
  atlasMap: document.querySelector("#atlas-map"),
  atlasMapSelection: document.querySelector("#atlas-map-selection"),
  atlasRevealSelectedButton: document.querySelector("#atlas-reveal-selected"),
  atlasZoomInButton: document.querySelector("#atlas-zoom-in"),
  atlasZoomOutButton: document.querySelector("#atlas-zoom-out"),
  atlasZoomResetButton: document.querySelector("#atlas-zoom-reset"),
  atlasShowRemainingButton: document.querySelector("#atlas-show-remaining"),
  atlasPosition: document.querySelector("#atlas-position"),
  flagStage: document.querySelector("#flag-stage"),
  flagFrame: document.querySelector("#flag-stage .flag-frame"),
  globleStage: document.querySelector("#globle-stage"),
  flagImage: document.querySelector("#flag-image"),
  flagMask: document.querySelector("#flag-mask"),
  globlePanel: document.querySelector("#globle-panel"),
  globeCanvas: document.querySelector("#globe-canvas"),
  globeZoomInButton: document.querySelector("#globe-zoom-in"),
  globeZoomOutButton: document.querySelector("#globe-zoom-out"),
  pageTitle: document.querySelector("#page-title"),
  roundTitle: document.querySelector("#flag-title"),
  statusMessage: document.querySelector("#status-message"),
  guessForm: document.querySelector("#guess-form"),
  countryInputLabel: document.querySelector('label[for="country-input"]'),
  countryInput: document.querySelector("#country-input"),
  guessButton: document.querySelector("#guess-button"),
  inputHint: document.querySelector("#input-hint"),
  countrySuggestions: document.querySelector("#country-suggestions"),
  spellingSuggestion: document.querySelector("#spelling-suggestion"),
  guessList: document.querySelector("#guess-list"),
  guessesTitle: document.querySelector("#guesses-title"),
  historyCount: document.querySelector("#history-count"),
  newGameButton: document.querySelector("#new-game-button"),
  giveUpButton: document.querySelector("#give-up-button"),
  shareButton: document.querySelector("#share-button"),
  themeToggle: document.querySelector("#theme-toggle"),
  themeToggleLabel: document.querySelector("#theme-toggle-label"),
  settingsButton: document.querySelector("#settings-button"),
  modalOverlay: document.querySelector("#modal-overlay"),
  modalClose: document.querySelector("#modal-close"),
  siteZoomOutButton: document.querySelector("#site-zoom-out"),
  siteZoomInButton: document.querySelector("#site-zoom-in"),
  siteZoomValue: document.querySelector("#site-zoom-value"),
  gameTimer: document.querySelector("#game-timer"),
  includeTaiwan: document.querySelector("#include-taiwan"),
  includeKosovo: document.querySelector("#include-kosovo"),
  soundToggle: document.querySelector("#sound-toggle")
};

export const confetti = {
  pieces: [],
  animationFrame: null,
  endAt: 0,
  context: null
};

export const hintView = { unlocked: 0, index: -1, targetCode: null };
